const express = require("express");
const dotenv = require("dotenv").config();
const { errorHandler } = require("./utils/errorHandler");
const colors = require("colors");
const connectDB = require("./config/db");
const port = process.env.PORT || 5000;
const cors = require("cors");
const app = express();
connectDB();
app.use(express.json());
app.use(cors());
app.use(express.urlencoded({ extended: false }));
app.use("/api", require("./routes/UserRoute"));
app.use(errorHandler);
app.listen(port, () => console.log(`server started on ${port}`));
